# Generated by Django 5.1.6 on 2025-02-26 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ahorro',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='ahorro',
            name='monto',
        ),
        migrations.AddField(
            model_name='ahorro',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ahorros_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ahorro',
            name='es_grupal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ahorro',
            name='monto_actual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='AhorroCompartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compartido', models.DateTimeField(auto_now_add=True)),
                ('ahorro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartido_con', to='finanzas.ahorro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ahorros_compartidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ahorro', 'usuario')},
            },
        ),
    ]
