# Generated by Django 5.1.6 on 2025-02-27 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_movimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudRetiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('aprobado', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ahorrocompartido',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ahorro',
            name='miembros',
            field=models.ManyToManyField(blank=True, related_name='ahorros', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='ahorrocompartido',
            constraint=models.UniqueConstraint(fields=('ahorro', 'usuario'), name='unique_ahorro_usuario'),
        ),
        migrations.AddField(
            model_name='solicitudretiro',
            name='ahorro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_retiro', to='finanzas.ahorro'),
        ),
        migrations.AddField(
            model_name='solicitudretiro',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_retiro', to=settings.AUTH_USER_MODEL),
        ),
    ]
